# Generated by Django 6.0.3 on 2026-03-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id', '-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
