# Generated by Django 6.0.3 on 2026-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_comments_message_alter_tasks_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments', verbose_name='Фото'),
        ),
    ]
