# Generated by Django 6.0.3 on 2026-04-18 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_attachments_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='photo',
        ),
        migrations.AddField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt'])], verbose_name='Файл'),
        ),
    ]
